# Generated by Django 4.1.2 on 2024-09-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(db_column='clienteRut', max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('modelo_vehiculo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('motorizacion', models.CharField(max_length=20)),
                ('id_patente', models.AutoField(db_column='idPatente', primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=20)),
                ('rut', models.ForeignKey(db_column='clienteRut', on_delete=django.db.models.deletion.CASCADE, to='gestionUser.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='gestionUser.genero'),
        ),
    ]
