# Generated by Django 5.1.1 on 2024-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(default='DEFAULT VALUE', max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.CharField(max_length=45),
        ),
    ]
